# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/memo-vault',
                'doc_host': 'https://DawnYe.github.io',
                'git_url': 'https://github.com/DawnYe/memo-vault',
                'lib_path': 'memo_vault'},
  'syms': {'memo_vault.core': {'memo_vault.core.foo': ('core.html#foo', 'memo_vault/core.py')}}}
